version: '3.5'

services:
  db:
    container_name: db
    image: mysql
    #volumes:
    #  - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auctiondb
      MYSQL_USER: auctionuser
      MYSQL_PASSWORD: auctionpassword
    networks:
      - db-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=auctionuser --password=auctionpassword --execute \"SHOW DATABASES;\""]
      interval: 10s
      timeout: 10s
      retries: 3

  backend:
    container_name: backend
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 app.asgi:application
    volumes:
      - ./backend:/code
    networks:
      - app-net
      - db-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://auctionuser:auctionpassword@db/auctiondb
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@localhost
      - DJANGO_SETTINGS_MODULE=app.settings
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-net
    depends_on:
      - backend
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always

volumes:
  db_data:

networks:
  db-net:
  app-net:
